---

# Solplanet JSON feldolgozás Python alatt


## Használt csomagok:


json, geojson, pandas




Python csomagok helye
https://pypi.org


---

In [9]:
## Solplavet JSON adatok feldolgozása !! havi összesített !!
import json
import datetime
import pandas as pd
from datetime import datetime

most = datetime.now()

file = 'kl1.json'  ## havi összesített
with open(file) as train_file:
    dict_train = json.load(train_file)

train = pd.DataFrame.from_dict(dict_train, orient='index')
train.reset_index(level=0, inplace=True)

print(train)              ## teljes json
print(train[0][1])        ## csak az aktuális adat sor
t0 = train[0][1]
me = t0['unit']           ## mértékegység
idosor = t0['x']          ## idősor
adatok = t0['data']       ## adatsorok
adatok_ac = adatok['ac']  ## egyen áram érték számsorok
adatok_dc = adatok['dc']  ## váltó áram érték számsorok
print(me)                 ## mértékegység
print(idosor)
print(adatok_ac)          ## egyen áram érték számsorok
print(adatok_dc)          ## váltó áram érték számsorok

print('------1------')

tartomany = range(12)

for i in tartomany:
    print(i, idosor[i ], 'Honap', adatok_dc[i],' MWh |', adatok_ac[i],' MWh |')

display(
    train[0][1]['unit'],           ## direkt mértékegység
    train[0][1]['x']   ,           ## direkt idosor
    train[0][1]['data']['ac'],     ## direkt ac
    train[0][1]['data']['dc'])  ## direkt dc

## összefüzés xls kiíráshoz
df_xls = pd.DataFrame({'IDO': train[0][1]['x'], 
                      'AC' : train[0][1]['data']['ac'],
                      'DC' : train[0][1]['data']['dc']
                      })
## pd.concat([df, series], axis = 1))

## érvényességidő kinyerése
szam = int(train[0][3])
timestamp = szam / 1000
date_time = datetime.fromtimestamp(timestamp)
#datum = date_time.strftime("%Y_%m_%d_%H:%M:%S")
datum = date_time.strftime("%Y_%m_%d")

display(df_xls)

## egy excelbe mentés formázás nélkül
# df_xls.to_excel(r"c:\Users\kecskemetil\Documents\sj\napelem\solplanet_napok\KL_json_evi_ossz.xlsx", sheet_name='Munka1',index=False)

writer = pd.ExcelWriter(r'c:\Users\kecskemetil\Documents\sj\napelem\solplanet_napok\KL_json_havi_ossz_'+datum+'.xlsx')
df_xls.to_excel(writer, sheet_name='Havi_ossz', index=False)

workbook  = writer.book
worksheet = writer.sheets['Havi_ossz']
(max_row, max_col) = df_xls.shape

indexek=[]
indexek.extend(df_xls.columns)

# Tábla formázás
column_settings = [{'header': column} for column in indexek]


worksheet.add_table(0, 0, max_row, max_col - 1, {'columns': column_settings}) ## index nélkül
worksheet.set_column(0, max_col - 1, 15) ## oszlop szélessség 15-re állítás   ## index nélkül

# Az excel állomány mentése
writer.close()

    index                                                  0
0     msg                                            Success
1  result  {'x': ['1', '2', '3', '4', '5', '6', '7', '8',...
2    code                                                200
3    time                                      1689834564345
{'x': ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'], 'unit': 'MWh', 'data': {'ac': [0.0, 0.63, 1.01, 1.09, 1.27, 1.3, 0.86, 0.0, 0.0, 0.0, 0.0, 0.0], 'dc': [0.0, 0.63, 1.01, 1.09, 1.27, 1.3, 0.86, 0.0, 0.0, 0.0, 0.0, 0.0]}}
MWh
['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12']
[0.0, 0.63, 1.01, 1.09, 1.27, 1.3, 0.86, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 0.63, 1.01, 1.09, 1.27, 1.3, 0.86, 0.0, 0.0, 0.0, 0.0, 0.0]
------1------
0 1 Honap 0.0  MWh | 0.0  MWh |
1 2 Honap 0.63  MWh | 0.63  MWh |
2 3 Honap 1.01  MWh | 1.01  MWh |
3 4 Honap 1.09  MWh | 1.09  MWh |
4 5 Honap 1.27  MWh | 1.27  MWh |
5 6 Honap 1.3  MWh | 1.3  MWh |
6 7 Honap 0.86  MWh | 0.86  MWh |
7 8 Honap 0.0  MWh | 0.0  MWh |
8 9 Honap 0.0  MWh | 0.0  MWh |
9 10 Honap 0.0  MWh | 0.0  MWh |
10 11 Honap 0.0  MWh | 0.0  MWh |
11 12 Honap 0.0  MWh | 0.0  MWh |

'MWh'

['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12']

[0.0, 0.63, 1.01, 1.09, 1.27, 1.3, 0.86, 0.0, 0.0, 0.0, 0.0, 0.0]

[0.0, 0.63, 1.01, 1.09, 1.27, 1.3, 0.86, 0.0, 0.0, 0.0, 0.0, 0.0]

   IDO    AC    DC
0    1  0.00  0.00
1    2  0.63  0.63
2    3  1.01  1.01
3    4  1.09  1.09
4    5  1.27  1.27
5    6  1.30  1.30
6    7  0.86  0.86
7    8  0.00  0.00
8    9  0.00  0.00
9   10  0.00  0.00
10  11  0.00  0.00
11  12  0.00  0.00

In [8]:
## Solplavet JSON adatok feldolgozása !! napi összesített !!
import json
import datetime
import pandas as pd
from datetime import datetime

most = datetime.now()

file = 'kl2.json'  ## havi összesített
with open(file) as train_file:
    dict_train = json.load(train_file)

train = pd.DataFrame.from_dict(dict_train, orient='index')
train.reset_index(level=0, inplace=True)

## érvényességidő kinyerése
szam = int(train[0][3])
timestamp = szam / 1000
date_time = datetime.fromtimestamp(timestamp)
#datum = date_time.strftime("%Y_%m_%d_%H:%M:%S")
datum = date_time.strftime("%Y_%m_%d")

## összefüzés xls kiíráshoz
df_xls = pd.DataFrame({'IDO': train[0][1]['x'], 
                       'AC' : train[0][1]['data']['ac'],
                       'DC' : train[0][1]['data']['dc']
                      })
## pd.concat([df, series], axis = 1))


## egy excelbe mentés formázás nélkül
# df_xls.to_excel(r"c:\Users\kecskemetil\Documents\sj\napelem\solplanet_napok\KL_json_evi_ossz.xlsx", sheet_name='Munka1',index=False)

writer = pd.ExcelWriter(r'c:\Users\kecskemetil\Documents\sj\napelem\solplanet_napok\KL_json_napi_ossz_'+datum+'.xlsx')
df_xls.to_excel(writer, sheet_name='Napi_ossz', index=False)

workbook  = writer.book
worksheet = writer.sheets['Napi_ossz']
(max_row, max_col) = df_xls.shape

indexek=[]
indexek.extend(df_xls.columns)

# Tábla formázás
column_settings = [{'header': column} for column in indexek]


worksheet.add_table(0, 0, max_row, max_col - 1, {'columns': column_settings}) ## index nélkül
worksheet.set_column(0, max_col - 1, 15) ## oszlop szélessség 15-re állítás   ## index nélkül

# Az excel állomány mentése
writer.close()

In [5]:
from datetime import datetime

t = datetime.now() # current date and time
print(t)
print(t.strftime('%m/%d/%Y'))


szoveg = '1689834375692'
szam = int(szoveg)
timestamp = szam / 1000
date_time = datetime.fromtimestamp(timestamp)
d = date_time.strftime("%Y_%m_%d_%H:%M:%S")
print(d)

2023-07-20 11:47:04.548280
07/20/2023
2023_07_20_08:26:15

In [13]:
## Solplavet JSON adatok feldolgozása !! napi részletezett !!
import json
import datetime
import pandas as pd
from datetime import datetime

most = datetime.now()



file = 'kl0.json'  ## havi összesített
with open(file) as train_file:
    dict_train = json.load(train_file)

train = pd.DataFrame.from_dict(dict_train, orient='index')
train.reset_index(level=0, inplace=True)

## érvényességidő kinyerése
szam = int(train[0][3])
timestamp = szam / 1000
date_time = datetime.fromtimestamp(timestamp)
#datum = date_time.strftime("%Y_%m_%d_%H:%M:%S")
datum = date_time.strftime("%Y_%m_%d")

display(    
    train[0][0]        ,           ## direkt státusz
    train[0][1]['unit'],           ## direkt mértékegység
    train[0][2],                   ## direct HTML üzenet kód
    train[0][3])                   ## direkt érvényesség dátumidő


## összefüzés xls kiíráshoz
df_xls = pd.DataFrame({'IDO': train[0][1]['x'], 
                      'AC' : train[0][1]['data']['ac'],
                      'DC' : train[0][1]['data']['dc']
                      })
## pd.concat([df, series], axis = 1))

display(datum, df_xls)

## egy excelbe mentés formázás nélkül
# df_xls.to_excel(r"c:\Users\kecskemetil\Documents\sj\napelem\solplanet_napok\KL_json_evi_ossz.xlsx", sheet_name='Munka1',index=False)

writer = pd.ExcelWriter(r'c:\Users\kecskemetil\Documents\sj\napelem\solplanet_napok\KL_json_napir_ossz_'+datum+'.xlsx')
df_xls.to_excel(writer, sheet_name='Napi_ossz', index=False)

workbook  = writer.book
worksheet = writer.sheets['Napi_ossz']
(max_row, max_col) = df_xls.shape

indexek=[]
indexek.extend(df_xls.columns)

# Tábla formázás
column_settings = [{'header': column} for column in indexek]


worksheet.add_table(0, 0, max_row, max_col - 1, {'columns': column_settings}) ## index nélkül
worksheet.set_column(0, max_col - 1, 15) ## oszlop szélessség 15-re állítás   ## index nélkül

# Az excel állomány mentése
writer.close()

'Success'

'kW'

200

1689834375692

'2023_07_20'

       IDO   AC   DC
0    00:00  0.0  0.0
1    00:10  0.0  0.0
2    00:20  0.0  0.0
3    00:30  0.0  0.0
4    00:40  0.0  0.0
..     ...  ...  ...
139  23:10  0.0  0.0
140  23:20  0.0  0.0
141  23:30  0.0  0.0
142  23:40  0.0  0.0
143  23:50  0.0  0.0

[144 rows x 3 columns]

In [44]:
## Solplavet JSON adatok feldolgozása !! napi részletezett !!
import json
import datetime
import pandas as pd
from datetime import datetime

most = datetime.now()

file = 'kl3_.json'  ## havi összesített  
file = 'kl3_.json'  ## havi összesített  // 1689850376561 // 1689850774374 //0 1689847790663

with open(file) as train_file:
    dict_train = json.load(train_file)

train = pd.DataFrame.from_dict(dict_train, orient='index')
train.reset_index(level=0, inplace=True)

## érvényességidő kinyerése
szam = int(train[0][3])
timestamp = szam / 1000
date_time = datetime.fromtimestamp(timestamp)
#datum = date_time.strftime("%Y_%m_%d_%H:%M:%S")
datum = date_time.strftime("%Y_%m_%d")

display(    
    train[0][0]        ,           ## direkt státusz
#    train[0][1],                   ## direkt mértékegység
    train[0][2],                   ## direct HTML üzenet kód
    train[0][3])                   ## direkt érvényesség dátumidő
, datum


## összefüzés xls kiíráshoz
df_xls = pd.DataFrame({'ido' : train[0][1]['data']['vpv']['x'], 
                       'vpv1_v' : train[0][1]['data']['vpv']['y'][0],
                       'vpv2_v' : train[0][1]['data']['vpv']['y'][1],
                       'ipv1_a' : train[0][1]['data']['ipv']['y'][0],
                       'ipv2_a' : train[0][1]['data']['ipv']['y'][1],
                       'vac1_V' : train[0][1]['data']['vac']['y'][0],
                       'vac2_V' : train[0][1]['data']['vac']['y'][1],
                       'vac3_V' : train[0][1]['data']['vac']['y'][2],
                       'iac1_A' : train[0][1]['data']['iac']['y'][0],
                       'iac2_A' : train[0][1]['data']['iac']['y'][1],
                       'iac3_A' : train[0][1]['data']['iac']['y'][2],
                       'pac_KWh' : train[0][1]['data']['pac']['y'][0],
                       'pdc1_kwh' : train[0][1]['data']['pdc']['y'][0],
                       'pdc2_kwh' : train[0][1]['data']['pdc']['y'][1],
                       'ppv_kwh' : train[0][1]['data']['ppv']['y'][0],
                       'fac_Hz' : train[0][1]['data']['fac']['y'][0],
                       'soc_%' : train[0][1]['data']['soc']['y'][0],
                       'temp_C' : train[0][1]['data']['temperature']['y'][0]
                      })

# display(datum, df_xls)

## egy excelbe mentés formázás nélkül
# df_xls.to_excel(r"c:\Users\kecskemetil\Documents\sj\napelem\solplanet_napok\KL_json_evi_ossz.xlsx", sheet_name='Munka1',index=False)

writer = pd.ExcelWriter(r'c:\Users\kecskemetil\Documents\sj\napelem\solplanet_napok\KL_json_napirh_ossz_'+ datum +'.xlsx')
df_xls.to_excel(writer, sheet_name='Napi_ossz', index=False)

workbook  = writer.book
worksheet = writer.sheets['Napi_ossz']
(max_row, max_col) = df_xls.shape

indexek=[]
indexek.extend(df_xls.columns)

# Tábla formázás
column_settings = [{'header': column} for column in indexek]


worksheet.add_table(0, 0, max_row, max_col - 1, {'columns': column_settings}) ## index nélkül
worksheet.set_column(0, max_col - 1, 15) ## oszlop szélessség 15-re állítás   ## index nélkül

# Az excel állomány mentése
writer.close()

'Success'

200

1689850774374

In [43]:
szam = 1689588590502 ## // 1689850376561 // 1689850774374 //0 1689847790663 #int(train[0][3])
## https://cloud.solplanet.net/api/chart/hyperbola?isno=SP00106032280241&id=283268&date=1689588590502
timestamp = szam / 1000
date_time = datetime.fromtimestamp(timestamp)
datum = date_time.strftime("%Y_%m_%d_%H:%M:%S")
#datum = date_time.strftime("%Y_%m_%d")
datum

'2023_07_17_12:09:50'

In [40]:
train

    index                                                  0
0     msg                                            Success
1  result  {'data': {'vpv': {'x': ['04:50', '04:55', '05:...
2    code                                                200
3    time                                      1689850774374